# Generated by Django 5.2.5 on 2025-08-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=5, verbose_name='Время')),
                ('deal', models.CharField(max_length=250, verbose_name='Дело')),
            ],
        ),
    ]
