# Generated by Django 5.2.5 on 2025-12-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deals',
            options={'verbose_name': 'Deal', 'verbose_name_plural': 'Deals'},
        ),
    ]
